name: Cargo Outdated

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  outdated:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: cargo-outdated
      run: cargo outdated --exit-code 1
      continue-on-error: true
    - run: echo ${{ steps.cargo-outdated.outputs }}
      if: ${{ steps.cargo-outdated.outcome == 'failure' }}
    
