name: Cargo Outdated

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-outdated:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: outdated
      run: |
        output=$(cargo outdated)
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=stdout::$output"
        cargo outdated --exit-code 1
      continue-on-error: true
    - run: echo "${{ steps.outdated.outputs.stdout }}"
      if: ${{ steps.outdated.outcome == 'failure' }}
    
