name: Cargo Outdated

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-outdated:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: cargo outdated
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        FORCE_COLOR: 3
      run: |
        npx zx <<'EOF'
          const content = (await $`cargo outdated -R`).toString();
          const resp = await fetch(process.env.DISCORD_WEBHOOK, {
            headers: {
                'content-type': 'application/json'
            },
            body: JSON.stringify({
                //username: process.env.,
                content: '```' + content + '```'
            })
          });
          console.log(resp.statusText);
        EOF
#     - name: cargo outdated
#       id: outdated
#       run: |
#         output=$(cargo outdated)
#         output="${output//'%'/'%25'}"
#         output="${output//$'\n'/'%0A'}"
#         output="${output//$'\r'/'%0D'}"
#         echo "::set-output name=stdout::$output"
#         cargo outdated --exit-code 1
#       continue-on-error: true
#     - name: Discord notification
#       env:
#         DISCORD_USERNAME: ${{ github.action_repository }}
#         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#       uses: Ilshidur/action-discord@0.3.2
#       with:
#         args: "```${{ steps.outdated.outputs.stdout }}```"
#       if: ${{ steps.outdated.outcome == 'failure' }}
    
