name: Cargo Oudated

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          .cargo/bin/
    - run: cargo install cargo-outdated
      if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
    - run: which cargo-outdated
    - run: cargo outdated --exit-code 1
